spring.application.name=Login
# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/LoginSystem
spring.datasource.username=postgres
spring.datasource.password=vinay@postgres

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# OAUTH2 - GOOGLE
# ===============================
spring.security.oauth2.client.registration.google.client-id=5641543104-84h63acjscq6t6u7b9evosve483vdigo.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# ===============================
# OAUTH2 - GITHUB
# ===============================
spring.security.oauth2.client.registration.github.client-id=Ov23liTkHBeU4HqqX74M
spring.security.oauth2.client.registration.github.client-secret=ccbf301d423f93a4959e841d60b7ab3d4a8688e6
spring.security.oauth2.client.registration.github.scope=user:email

# ===============================
# JWT
# ===============================
jwt.secret=THIS_IS_A_32_CHAR_MINIMUM_JWT_SECRET_KEY_123456
jwt.expiration=86400000

# Max file size
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
